[package]
name = "rspace_plus_plus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
heed = "0.11.0"

[[bin]]
name = "rspace_plus_plus"
path = "main.rs"
